name: The Imaji Nation
favicon: null
layout_spectrum: 0.8998423938173801
typography_spectrum: 0.17618690780363977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7365253074094653
  lightness: 0.3459617227781564
  saturation: 0.6318255099467933
  rhythmicContrast: 0.8220162133220583
purpose: []
